[2023-03-16T09:32:09.490+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_python_operator_v4.greet scheduled__2023-03-15T00:00:00+00:00 [queued]>
[2023-03-16T09:32:09.500+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_python_operator_v4.greet scheduled__2023-03-15T00:00:00+00:00 [queued]>
[2023-03-16T09:32:09.501+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-16T09:32:09.501+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 6
[2023-03-16T09:32:09.502+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-16T09:32:09.519+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): greet> on 2023-03-15 00:00:00+00:00
[2023-03-16T09:32:09.522+0000] {standard_task_runner.py:55} INFO - Started process 950 to run task
[2023-03-16T09:32:09.524+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_python_operator_v4', 'greet', 'scheduled__2023-03-15T00:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/python_operator.py', '--cfg-path', '/tmp/tmpmvpwjeki']
[2023-03-16T09:32:09.526+0000] {standard_task_runner.py:83} INFO - Job 21: Subtask greet
[2023-03-16T09:32:09.590+0000] {task_command.py:388} INFO - Running <TaskInstance: dag_with_python_operator_v4.greet scheduled__2023-03-15T00:00:00+00:00 [running]> on host c3799dfdd69d
[2023-03-16T09:32:09.661+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Mr.Phi
AIRFLOW_CTX_DAG_ID=dag_with_python_operator_v4
AIRFLOW_CTX_TASK_ID=greet
AIRFLOW_CTX_EXECUTION_DATE=2023-03-15T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-15T00:00:00+00:00
[2023-03-16T09:32:09.662+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/python_operator.py", line 14, in greet
    name = ti.xcoms_pull(task_id='get_name')
AttributeError: 'TaskInstance' object has no attribute 'xcoms_pull'
[2023-03-16T09:32:09.676+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_python_operator_v4, task_id=greet, execution_date=20230315T000000, start_date=20230316T093209, end_date=20230316T093209
[2023-03-16T09:32:09.691+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 21 for task greet ('TaskInstance' object has no attribute 'xcoms_pull'; 950)
[2023-03-16T09:32:09.697+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-16T09:32:09.716+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
