[2023-03-16T09:35:06.840+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_python_operator_v4.greet manual__2023-03-16T09:32:45.934498+00:00 [queued]>
[2023-03-16T09:35:06.853+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_python_operator_v4.greet manual__2023-03-16T09:32:45.934498+00:00 [queued]>
[2023-03-16T09:35:06.854+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-16T09:35:06.855+0000] {taskinstance.py:1283} INFO - Starting attempt 2 of 7
[2023-03-16T09:35:06.855+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-16T09:35:06.874+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): greet> on 2023-03-16 09:32:45.934498+00:00
[2023-03-16T09:35:06.879+0000] {standard_task_runner.py:55} INFO - Started process 1063 to run task
[2023-03-16T09:35:06.882+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_python_operator_v4', 'greet', 'manual__2023-03-16T09:32:45.934498+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/python_operator.py', '--cfg-path', '/tmp/tmpktrvsfpb']
[2023-03-16T09:35:06.884+0000] {standard_task_runner.py:83} INFO - Job 25: Subtask greet
[2023-03-16T09:35:06.954+0000] {task_command.py:388} INFO - Running <TaskInstance: dag_with_python_operator_v4.greet manual__2023-03-16T09:32:45.934498+00:00 [running]> on host c3799dfdd69d
[2023-03-16T09:35:07.029+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Mr.Phi
AIRFLOW_CTX_DAG_ID=dag_with_python_operator_v4
AIRFLOW_CTX_TASK_ID=greet
AIRFLOW_CTX_EXECUTION_DATE=2023-03-16T09:32:45.934498+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-16T09:32:45.934498+00:00
[2023-03-16T09:35:07.030+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/python_operator.py", line 14, in greet
    name = ti.xcom_pull(task_id='get_name')
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
TypeError: xcom_pull() got an unexpected keyword argument 'task_id'
[2023-03-16T09:35:07.042+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_python_operator_v4, task_id=greet, execution_date=20230316T093245, start_date=20230316T093506, end_date=20230316T093507
[2023-03-16T09:35:07.054+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 25 for task greet (xcom_pull() got an unexpected keyword argument 'task_id'; 1063)
[2023-03-16T09:35:07.094+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-16T09:35:07.113+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
