[2023-03-16T09:32:47.971+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_python_operator_v4.greet manual__2023-03-16T09:32:45.934498+00:00 [queued]>
[2023-03-16T09:32:47.982+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_python_operator_v4.greet manual__2023-03-16T09:32:45.934498+00:00 [queued]>
[2023-03-16T09:32:47.983+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-16T09:32:47.983+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 6
[2023-03-16T09:32:47.984+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-16T09:32:48.001+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): greet> on 2023-03-16 09:32:45.934498+00:00
[2023-03-16T09:32:48.004+0000] {standard_task_runner.py:55} INFO - Started process 978 to run task
[2023-03-16T09:32:48.007+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_python_operator_v4', 'greet', 'manual__2023-03-16T09:32:45.934498+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/python_operator.py', '--cfg-path', '/tmp/tmptqzttdo9']
[2023-03-16T09:32:48.008+0000] {standard_task_runner.py:83} INFO - Job 24: Subtask greet
[2023-03-16T09:32:48.074+0000] {task_command.py:388} INFO - Running <TaskInstance: dag_with_python_operator_v4.greet manual__2023-03-16T09:32:45.934498+00:00 [running]> on host c3799dfdd69d
[2023-03-16T09:32:48.150+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Mr.Phi
AIRFLOW_CTX_DAG_ID=dag_with_python_operator_v4
AIRFLOW_CTX_TASK_ID=greet
AIRFLOW_CTX_EXECUTION_DATE=2023-03-16T09:32:45.934498+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-16T09:32:45.934498+00:00
[2023-03-16T09:32:48.151+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/python_operator.py", line 14, in greet
    name = ti.xcoms_pull(task_id='get_name')
AttributeError: 'TaskInstance' object has no attribute 'xcoms_pull'
[2023-03-16T09:32:48.162+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_python_operator_v4, task_id=greet, execution_date=20230316T093245, start_date=20230316T093247, end_date=20230316T093248
[2023-03-16T09:32:48.174+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 24 for task greet ('TaskInstance' object has no attribute 'xcoms_pull'; 978)
[2023-03-16T09:32:48.180+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-16T09:32:48.198+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
