[2023-03-21T11:35:34.922+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_python_operator_v05.install_odbc_3 scheduled__2023-03-20T00:00:00+00:00 [queued]>
[2023-03-21T11:35:34.933+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_python_operator_v05.install_odbc_3 scheduled__2023-03-20T00:00:00+00:00 [queued]>
[2023-03-21T11:35:34.934+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-21T11:35:34.934+0000] {taskinstance.py:1283} INFO - Starting attempt 3 of 6
[2023-03-21T11:35:34.935+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-21T11:35:34.953+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): install_odbc_3> on 2023-03-20 00:00:00+00:00
[2023-03-21T11:35:34.957+0000] {standard_task_runner.py:55} INFO - Started process 8477 to run task
[2023-03-21T11:35:34.960+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_python_operator_v05', 'install_odbc_3', 'scheduled__2023-03-20T00:00:00+00:00', '--job-id', '293', '--raw', '--subdir', 'DAGS_FOLDER/python_operator.py', '--cfg-path', '/tmp/tmpby2nyi_z']
[2023-03-21T11:35:34.962+0000] {standard_task_runner.py:83} INFO - Job 293: Subtask install_odbc_3
[2023-03-21T11:35:35.028+0000] {task_command.py:388} INFO - Running <TaskInstance: dag_with_python_operator_v05.install_odbc_3 scheduled__2023-03-20T00:00:00+00:00 [running]> on host cfacfd39f993
[2023-03-21T11:35:35.108+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Mr.Phi
AIRFLOW_CTX_DAG_ID=dag_with_python_operator_v05
AIRFLOW_CTX_TASK_ID=install_odbc_3
AIRFLOW_CTX_EXECUTION_DATE=2023-03-20T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-20T00:00:00+00:00
[2023-03-21T11:35:35.109+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-21T11:35:35.110+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'apt-get update']
[2023-03-21T11:35:35.118+0000] {subprocess.py:86} INFO - Output:
[2023-03-21T11:35:35.680+0000] {subprocess.py:93} INFO - Reading package lists...
[2023-03-21T11:35:35.689+0000] {subprocess.py:93} INFO - E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
[2023-03-21T11:35:35.690+0000] {subprocess.py:93} INFO - E: Unable to lock directory /var/lib/apt/lists/
[2023-03-21T11:35:35.690+0000] {subprocess.py:97} INFO - Command exited with return code 100
[2023-03-21T11:35:35.702+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 100.
[2023-03-21T11:35:35.708+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_python_operator_v05, task_id=install_odbc_3, execution_date=20230320T000000, start_date=20230321T113534, end_date=20230321T113535
[2023-03-21T11:35:35.724+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 293 for task install_odbc_3 (Bash command failed. The command returned a non-zero exit code 100.; 8477)
[2023-03-21T11:35:35.735+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-21T11:35:35.757+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
